[package]
name = "hanoi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
derive_more = {version="1.0.0", features= ["from", "into"]}
itertools = "0.13.0"
pest = "2.7.13"
pest_derive = "2.7.13"
ratatui = "0.28.1"
typed-index-collections = "3.1.0"
